### ISSUE TITLE
Задание 2, задача 4 не верная

### ISSUE THREAD

**Issue by tim-teacher** [DaryaTratseuskaya/javapvt5#1]
HomeWork2/src/main/java/by/itacademy/task2/Task4.java
работает только для 3х чисел

**Comment by DaryaTratseuskaya** [comment]
а напишите, пожалуйста, число, для которого не работает) потому что я тестирую и у меня любое число от 12 до 123456789 проходит, или нужен какой-то более универсальный алгоритм?

**Comment by DaryaTratseuskaya** [comment]
а я, кажется, поняла, строговозрастающая должна на 1 отличаться, буду фиксить)

**Comment by DaryaTratseuskaya** [comment]
Fixed
